### ISSUE TITLE
verifyTime is not used nor documented

### ISSUE THREAD

**Issue by Guuz** [tngan/express-saml2#54]
Hello,

I thought this lib would check the `notBefore` and `notOnOrAfter` fields. There's a function called `verifyTime` that does this. Though this function is never used anywhere. Neither is there documentation about how to use it yourself.

I have done the following (which seems to work):

```js
// simplified example
sp.parseLoginResponse(idp, 'post', req, parseResult => {
    const {conditions} = parseResult.extract;
    const notBefore = conditions.notbefore;
    const notOnOrAfter = conditions.notonorafter;
    const validTimeframe = sp.verifyTime(notBefore, notOnOrAfter);

    if (!validTimeframe) {
      console.warn(`SAML message has expired. notBefore: ${notBefore} notOnOrAfter: ${notOnOrAfter}`);
      res.sendStatus(500);
    } else {
      res.send(parseResult.extract.nameid);
    }
  });
```

**Comment by tngan** [comment]
@Guuz This function is exposed to both idp and sp instance (in fact, the time conditions are optional in document [P.21](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf), the `parseLoginResponse` is a helper function to handle the xml document, and leave this option to developers.

I think it would be good to include before the callback is invoked, once the message has time conditions, it should be checked. 

I am welcome to any pull request. Since we are working on v2 right now, so new features and enhancements would not be updated in v1, v1 only updates when bug is discovered.

**Comment by aaronpankratz** [comment]
I don't see this function on the types for ServiceProvider  in `types/index.d.ts` and I get `Property 'verifyTime' does not exist on type 'ServiceProvider'.` Am I missing something?

**Comment by aaronpankratz** [comment]
@tngan What is the recommended approach to use `verifyTime` with TypeScript?
