### ISSUE TITLE
Confused about ipd1 vs idp2..?

### ISSUE THREAD

**Issue by danscrima** [tngan/express-saml2#58]
I'm certainly not an expert in saml, but I'm trying to understand your full example and I'm confused why there's a different idp1 vs idp2? Those instances are both set to the same configuration, why are both required and what might the actual difference be in how they're used.. Thanks!

**Comment by tngan** [comment]
@danscrima Thanks for your question. They are two separate identity providers. In fact, the entity can be described by using metadata, idp1 uses `metadata_idp1.xml` whereas idp2 uses `metadata_idp2.xml`, and they have different service endpoints.

We need additional configurations for full features, for example, we need private key to sign the request/response, the key file may have passphrase. However, metadata is supposed to be publicly distributed commonly and metadata has a standard definition. Therefore, the additional configurations are used to configure entity regarding to your use cases. 

The simplest way to define an entity is to import the metadata in this module.

The reason why there are idp1 and idp2 is because we support multiple identity providers. For example, your application A (SP) delegates the authentication to identity provider A but your application B (another SP) delegates that to identity provider B. I don't know if this use case is rare, then we leave that option to developers. In order words, this module supports both

+ multiple SPs -> same IdP 
+ multiple SPs -> different IdP (e.g. SP1 -> IdP1, SP2 -> IdP2)

**Comment by danscrima** [comment]
Ok great, thanks very much for the clarification, I appreciate it! This is such great work and will help us out a lot! Cheers.

**Comment by tngan** [comment]
@danscrima Good to know. This module is now being revamped, we will announce v2 before the middle of May (alpha is released last month). If you like this module, feel free to be your stargazer.
